name: CI

# Controls when the workflows will run
on:
  # Triggers the workflows on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflows manually from the Actions tab
  workflow_dispatch:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: https://api.getpostman.com/collections/12584448-c8c5a445-3c35-44f3-a023-761fe0252d07?apikey=PMAK-61fe9508434e4f05f01c9898-80138aa7f65eee0bc3c3e07974be084cd9
          environment: https://api.getpostman.com/environments/12584448-81292e6a-035e-44dd-8fc2-b54ca8cf1ff4?apikey=PMAK-61fe9508434e4f05f01c9898-80138aa7f65eee0bc3c3e07974be084cd9